### ISSUE TITLE
train_localisation_model: download link seems broken

### ISSUE THREAD

**Issue by mschoeffler** [TWOEARS/examples#1]
It seems like a download link of the example "train_localisation_model" is broken.

If I call the function "localise" in the "train_localisation_model" folder, I get the following error:

> Downloading file https://dev.qu.tu-berlin.de/projects/twoears-database/repository/revisions/master/raw//learned_models/LocationKS/mit/mit.str
> Error using xml.dbDownloadFile (line 39)
> Download failed
> (url=https://dev.qu.tu-berlin.de/projects/twoears-database/repository/revisions/master/raw//learned_models/LocationKS/mit/mit.str)
> Error in xml.dbGetFile (line 87)
>           filename = dbDownloadFile(filename);
> ...

All other examples did work (tested with Windows 7, Matlab R2014b, TwoEars-1.0.1).

**Comment by hagenw** [comment]
Hi.

The file `mit.str` is indeed not part of the database. You should have created it yourself before by running:

``` Matlab
>> train('mit', 'SceneDescriptionMIT.xml', 5);
```

After that the file should be in your local path under `learned_models/LocationKS/mit/mit.str`, this is where the `xml.dbGetFile()` functions looks first. Did you run the `train` command before running `localise`? Did you changed the path in Matlab in between?

**Comment by mschoeffler** [comment]
Hi, you are right. I messed up something with the `train` part. All examples are working perfectly on my system. Thanks!
